In [3]:
import pandas as pd 
import utils as ut
import requests
from bs4 import BeautifulSoup
from urllib.parse import urlencode, urljoin

Aca me ubico en la carpeta de los archivos necesarios

In [4]:
%cd C:\\Users\\Familia Lara Pernia\\Desktop\\Proyecto2_SiniestrosViales_Henry
%pwd

C:\Users\Familia Lara Pernia\Desktop\Proyecto2_SiniestrosViales_Henry

'C:\\Users\\Familia Lara Pernia\\Desktop\\Proyecto2_SiniestrosViales_Henry'

Cargamos la data a trabajar

In [7]:
hechos = pd.read_csv("data/csv/hechos_limpio.csv")
victimas = pd.read_csv("data/csv/victimas_limpio.csv")

Visualizamos nuestros df

In [8]:
hechos.head()

,Hechos_Id,Número De Victimas,Fecha,Año,Mes,Dia,Día Semana,Estación,Hora,Franja Horaria,...,Calle,Cruce,Dirección Normalizada,Comuna,XY (CABA),Pos X,Pos Y,Participantes,Víctima,Acusado
0,2016-0001,1,2016-01-01,2016,Enero,1,Viernes,Verano,04:00:00,4,...,PIEDRA BUENA AV.,True,"PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",Comuna 8,Point (98896.78238426 93532.43437792),-58.475340,-34.687570,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,Enero,2,Sábado,Verano,01:15:00,1,...,"PAZ, GRAL. AV.",True,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",Comuna 9,Point (95832.05571093 95505.41641999),-58.508775,-34.669777,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,Enero,3,Domingo,Verano,07:00:00,7,...,ENTRE RIOS AV.,False,ENTRE RIOS AV. 2034,Comuna 1,Point (106684.29090040 99706.57687843),-58.390403,-34.631894,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,Enero,10,Domingo,Verano,00:00:00,0,...,LARRAZABAL AV.,True,"LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",Comuna 8,Point (99840.65224780 94269.16534422),-58.465039,-34.680930,MOTO-SD,MOTO,SD
4,2016-0005,1,2016-01-21,2016,Enero,21,Jueves,Verano,05:20:00,5,...,SAN JUAN AV.,True,"SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",Comuna 1,Point (106980.32827929 100752.16915795),-58.387183,-34.622466,MOTO-PASAJEROS,MOTO,PASAJEROS

In [9]:
victimas.head()

   Hechos_Id        Rol       Sexo  Edad Rango Etario
0  2016-0001  CONDUCTOR  MASCULINO    19        19-25
1  2016-0002  CONDUCTOR  MASCULINO    70          61+
2  2016-0003  CONDUCTOR  MASCULINO    30        26-40
3  2016-0004  CONDUCTOR  MASCULINO    18        19-25
4  2016-0005  CONDUCTOR  MASCULINO    29        26-40

Unimos los df mediante la columna 'Hechos_Id'

In [10]:
accidentes = pd.merge(hechos, victimas, on='Hechos_Id', how='left')
accidentes

,Hechos_Id,Número De Victimas,Fecha,Año,Mes,Dia,Día Semana,Estación,Hora,Franja Horaria,...,XY (CABA),Pos X,Pos Y,Participantes,Víctima,Acusado,Rol,Sexo,Edad,Rango Etario
0,2016-0001,1,2016-01-01,2016,Enero,1,Viernes,Verano,04:00:00,4,...,Point (98896.78238426 93532.43437792),-58.475340,-34.687570,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,19,19-25
1,2016-0002,1,2016-01-02,2016,Enero,2,Sábado,Verano,01:15:00,1,...,Point (95832.05571093 95505.41641999),-58.508775,-34.669777,AUTO-PASAJEROS,AUTO,PASAJEROS,CONDUCTOR,MASCULINO,70,61+
2,2016-0003,1,2016-01-03,2016,Enero,3,Domingo,Verano,07:00:00,7,...,Point (106684.29090040 99706.57687843),-58.390403,-34.631894,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,30,26-40
3,2016-0004,1,2016-01-10,2016,Enero,10,Domingo,Verano,00:00:00,0,...,Point (99840.65224780 94269.16534422),-58.465039,-34.680930,MOTO-SD,MOTO,SD,CONDUCTOR,MASCULINO,18,19-25
4,2016-0005,1,2016-01-21,2016,Enero,21,Jueves,Verano,05:20:00,5,...,Point (106980.32827929 100752.16915795),-58.387183,-34.622466,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,29,26-40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,2021-0093,1,2021-12-13,2021,Diciembre,13,Lunes,Verano,17:10:00,17,...,Point (102728.60090138 98186.24929177),-58.433538,-34.645616,MOTO-AUTO,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,18,19-25
712,2021-0094,1,2021-12-20,2021,Diciembre,20,Lunes,Verano,01:10:00,1,...,Point (99624.29795829 97569.69801131),-58.467398,-34.651178,MOTO-AUTO,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,43,41-60
713,2021-0095,1,2021-12-30,2021,Diciembre,30,Jueves,Verano,00:43:00,0,...,Point (99116.45492358 101045.23284826),-58.472934,-34.619847,MOTO-CARGAS,MOTO,CARGAS,CONDUCTOR,MASCULINO,27,26-40
714,2021-0096,1,2021-12-15,2021,Diciembre,15,Miércoles,Verano,10:30:00,10,...,Point (99324.54463985 97676.26932409),-58.470668,-34.650217,AUTO-CARGAS,AUTO,CARGAS,CONDUCTOR,MASCULINO,60,61+
715,2021-0097,1,2021-11-18,2021,Noviembre,18,Jueves,Primavera,06:10:00,6,...,Point (107664.16647795 104708.63962087),-58.379762,-34.586796,BICICLETA-AUTO,BICICLETA,AUTO,CICLISTA,MASCULINO,53,41-60

In [11]:
# Visualizamos el sumario del nuevo df
ut.data_summ(accidentes)

Total filas:  716

Total filas nulas:  0

Total filas duplicadas:  0

,Columnas,Tipo_Dato,No_miss_Qty,%Missing,Missing_Qty
0,Hechos_Id,[<class 'str'>],716,0.0,0
1,Número De Victimas,[<class 'int'>],716,0.0,0
2,Fecha,[<class 'str'>],716,0.0,0
3,Año,[<class 'int'>],716,0.0,0
4,Mes,[<class 'str'>],716,0.0,0
5,Dia,[<class 'int'>],716,0.0,0
6,Día Semana,[<class 'str'>],716,0.0,0
7,Estación,[<class 'str'>],716,0.0,0
8,Hora,[<class 'str'>],716,0.0,0
9,Franja Horaria,[<class 'int'>],716,0.0,0
10,Lugar Del Hecho,[<class 'str'>],716,0.0,0
11,Tipo De Calle,[<class 'str'>],716,0.0,0
12,Calle,[<class 'str'>],716,0.0,0
13,Cruce,[<class 'bool'>],716,0.0,0
14,Dirección Normalizada,[<class 'str'>],716,0.0,0
15,Comuna,[<class 'str'>],716,0.0,0
16,XY (CABA),[<class 'str'>],716,0.0,0
17,Pos X,[<class 'float'>],716,0.0,0
18,Pos Y,[<class 'float'>],716,0.0,0
19,Participantes,[<class 'str'>],716,0.0,0
20,Víctima,[<class 'str'>],716,0.0,0
21,Acusado,[<class 'str'>],716,0.0,0
22,Rol,[<class 'str'>],716,0.0,0
23,Sexo,[<class 'str'>],716,0.0,0
24,Edad,[<class 'int'>],716,0.0,0
25,Rango Etario,[<class 'str'>],716,0.0,0

In [12]:
ut.count_value_per_column(accidentes, 'SD')

Cuenta de 'SD' en la columna Hechos_Id: 0
Cuenta de 'SD' en la columna Número De Victimas: 0
Cuenta de 'SD' en la columna Fecha: 0
Cuenta de 'SD' en la columna Año: 0
Cuenta de 'SD' en la columna Mes: 0
Cuenta de 'SD' en la columna Dia: 0
Cuenta de 'SD' en la columna Día Semana: 0
Cuenta de 'SD' en la columna Estación: 0
Cuenta de 'SD' en la columna Hora: 0
Cuenta de 'SD' en la columna Franja Horaria: 0
Cuenta de 'SD' en la columna Lugar Del Hecho: 0
Cuenta de 'SD' en la columna Tipo De Calle: 0
Cuenta de 'SD' en la columna Calle: 0
Cuenta de 'SD' en la columna Cruce: 0
Cuenta de 'SD' en la columna Dirección Normalizada: 8
Cuenta de 'SD' en la columna Comuna: 0
Cuenta de 'SD' en la columna XY (CABA): 0
Cuenta de 'SD' en la columna Pos X: 0
Cuenta de 'SD' en la columna Pos Y: 0
Cuenta de 'SD' en la columna Participantes: 0
Cuenta de 'SD' en la columna Víctima: 9
Cuenta de 'SD' en la columna Acusado: 22
Cuenta de 'SD' en la columna Rol: 0
Cuenta de 'SD' en la columna Sexo: 0
Cuenta de 'SD' en la columna Edad: 0
Cuenta de 'SD' en la columna Rango Etario: 0

Ahora vamos a extraer datos de una API del sitio web del Gobierno de Buenos Aires y formular una función para obtener los barrios en base a las coordenadas dadas por las columnas 'Pos X' y 'Pos Y'

In [13]:
def get_vecindario(fila):
    """
    Recupera el nombre del vecindario según las coordenadas geográficas mediante una API externa.

    Parametros:
    -----------
       fila (pandas.Series): una fila de un DataFrame que contiene las columnas 'Pos X' y 'Pos Y'.

    Retorna:
    --------
        str: El nombre del vecindario si se encuentra, o "Desconocido" si no se encuentra o hay un error.
    """
    # URL base para la API externa
    base_url = "https://datosabiertos-usig-apis.buenosaires.gob.ar/datos_utiles"
    
    # Parámetros de consulta para la solicitud de API
    parametros = {
        "x": fila["Pos X"],
        "y": fila["Pos Y"],
        "formato": "json"
    }
    
    # Creamos la URL completa con parámetros de consulta
    full_url = urljoin(base_url, '?' + urlencode(parametros))

    try:
        # Realizamos la solicitud HTTP
        response = requests.get(full_url)
        
        # Verificamos el código de estado de la respuesta.
        response.raise_for_status()
        
        # Analiza JSON y obtiene el nombre del vecindario si está presente
        data = response.json()
        return data.get("barrio", "Desconocido")
    
    except requests.exceptions.RequestException as e:
        print("Error al realizar la solicitud:", e)
        return "Desconocido"

In [14]:
# Aplicamos la funcion en la nueva columna'Barrio'
accidentes["Barrio"] = accidentes[["Pos Y", "Pos X"]].apply(get_vecindario, axis=1)
# Observamos la columna
accidentes["Barrio"]

0        Villa Riachuelo
1
2           Constitucion
3           Villa Lugano
4           Constitucion
             ...
711     Parque Chacabuco
712    Parque Avellaneda
713               Flores
714    Parque Avellaneda
715               Retiro
Name: Barrio, Length: 716, dtype: object

In [15]:
accidentes

,Hechos_Id,Número De Victimas,Fecha,Año,Mes,Dia,Día Semana,Estación,Hora,Franja Horaria,...,Pos X,Pos Y,Participantes,Víctima,Acusado,Rol,Sexo,Edad,Rango Etario,Barrio
0,2016-0001,1,2016-01-01,2016,Enero,1,Viernes,Verano,04:00:00,4,...,-58.475340,-34.687570,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,19,19-25,Villa Riachuelo
1,2016-0002,1,2016-01-02,2016,Enero,2,Sábado,Verano,01:15:00,1,...,-58.508775,-34.669777,AUTO-PASAJEROS,AUTO,PASAJEROS,CONDUCTOR,MASCULINO,70,61+,
2,2016-0003,1,2016-01-03,2016,Enero,3,Domingo,Verano,07:00:00,7,...,-58.390403,-34.631894,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,30,26-40,Constitucion
3,2016-0004,1,2016-01-10,2016,Enero,10,Domingo,Verano,00:00:00,0,...,-58.465039,-34.680930,MOTO-SD,MOTO,SD,CONDUCTOR,MASCULINO,18,19-25,Villa Lugano
4,2016-0005,1,2016-01-21,2016,Enero,21,Jueves,Verano,05:20:00,5,...,-58.387183,-34.622466,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,29,26-40,Constitucion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,2021-0093,1,2021-12-13,2021,Diciembre,13,Lunes,Verano,17:10:00,17,...,-58.433538,-34.645616,MOTO-AUTO,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,18,19-25,Parque Chacabuco
712,2021-0094,1,2021-12-20,2021,Diciembre,20,Lunes,Verano,01:10:00,1,...,-58.467398,-34.651178,MOTO-AUTO,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,43,41-60,Parque Avellaneda
713,2021-0095,1,2021-12-30,2021,Diciembre,30,Jueves,Verano,00:43:00,0,...,-58.472934,-34.619847,MOTO-CARGAS,MOTO,CARGAS,CONDUCTOR,MASCULINO,27,26-40,Flores
714,2021-0096,1,2021-12-15,2021,Diciembre,15,Miércoles,Verano,10:30:00,10,...,-58.470668,-34.650217,AUTO-CARGAS,AUTO,CARGAS,CONDUCTOR,MASCULINO,60,61+,Parque Avellaneda
715,2021-0097,1,2021-11-18,2021,Noviembre,18,Jueves,Primavera,06:10:00,6,...,-58.379762,-34.586796,BICICLETA-AUTO,BICICLETA,AUTO,CICLISTA,MASCULINO,53,41-60,Retiro

In [16]:
ut.data_summ(accidentes)

Total filas:  716

Total filas nulas:  0

Total filas duplicadas:  0

,Columnas,Tipo_Dato,No_miss_Qty,%Missing,Missing_Qty
0,Hechos_Id,[<class 'str'>],716,0.0,0
1,Número De Victimas,[<class 'int'>],716,0.0,0
2,Fecha,[<class 'str'>],716,0.0,0
3,Año,[<class 'int'>],716,0.0,0
4,Mes,[<class 'str'>],716,0.0,0
5,Dia,[<class 'int'>],716,0.0,0
6,Día Semana,[<class 'str'>],716,0.0,0
7,Estación,[<class 'str'>],716,0.0,0
8,Hora,[<class 'str'>],716,0.0,0
9,Franja Horaria,[<class 'int'>],716,0.0,0
10,Lugar Del Hecho,[<class 'str'>],716,0.0,0
11,Tipo De Calle,[<class 'str'>],716,0.0,0
12,Calle,[<class 'str'>],716,0.0,0
13,Cruce,[<class 'bool'>],716,0.0,0
14,Dirección Normalizada,[<class 'str'>],716,0.0,0
15,Comuna,[<class 'str'>],716,0.0,0
16,XY (CABA),[<class 'str'>],716,0.0,0
17,Pos X,[<class 'float'>],716,0.0,0
18,Pos Y,[<class 'float'>],716,0.0,0
19,Participantes,[<class 'str'>],716,0.0,0
20,Víctima,[<class 'str'>],716,0.0,0
21,Acusado,[<class 'str'>],716,0.0,0
22,Rol,[<class 'str'>],716,0.0,0
23,Sexo,[<class 'str'>],716,0.0,0
24,Edad,[<class 'int'>],716,0.0,0
25,Rango Etario,[<class 'str'>],716,0.0,0
26,Barrio,[<class 'str'>],716,0.0,0

Podemos ver que la nueva columna tiene valores vacíos pero no son datos nulos. Ahora vamos a analizar esos valores.

In [17]:
accidentes[accidentes.Barrio == ''][['Comuna', 'Barrio', 'Cruce', 'Calle', 'Lugar Del Hecho', 'Pos X', 'Pos Y']]

,Comuna,Barrio,Cruce,Calle,Lugar Del Hecho,Pos X,Pos Y
1,Comuna 9,,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y AV DE LOS CORRALES,-58.508775,-34.669777
7,Comuna 9,,True,"PAZ, GRAL. AV.",AV GENERAL PAZ Y AV DE LOS CORRALES,-58.508775,-34.669777
17,Comuna 8,,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y AV 27 DE FEBRERO,-58.462450,-34.705250
27,Comuna 8,,True,"PAZ, GRAL. AV.",AV GRAL PAZ COLECTORA Y ZUVIRIA,-58.496835,-34.678927
33,Comuna 13,,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y AV DEL LIBERTADOR,-58.467435,-34.534769
39,Comuna 13,,False,"LUGONES, LEOPOLDO AV.",AUTOPISTA LUGONES PK 10000,0.000000,0.000000
41,Comuna 8,,True,AUTOPISTA DELLEPIANE LUIS TTE. GRAL.,AU LUIS DELLEPIANE Y AV GRAL PAZ,-58.486954,-34.687952
52,Comuna 8,,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y RODOLFO SCAPINO,-58.498966,-34.677321
69,Comuna 13,,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y AV LIBERTADOR,-58.467435,-34.534769
75,Comuna 11,,True,MOSCONI GENERAL AV.,AV GRAL MOSCONI Y AV GRAL PAZ,-58.523406,-34.597988
131,Comuna 11,,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y AV GENERAL MOSCONI,-58.523406,-34.597988
140,Comuna 0,,False,AUTOPISTA 25 DE MAYO,AUTOPISTA 25 DE MAYO,0.000000,0.000000
151,Comuna 12,,True,"PAZ, GRAL. AV.",AV. GRAL. PAZ Y AV. R. BALBIN,-58.500738,-34.549795
158,Comuna 9,,True,"PAZ, GRAL. AV.",AV. GRAL. PAZ Y AV. DE LOS CORRALES,-58.508775,-34.669777
188,Comuna 8,,True,"PAZ, GRAL. AV.",AV. GRAL. PAZ Y GOLETA JULIA,-58.494138,-34.680957
203,Comuna 9,,True,"PAZ, GRAL. AV.",AV. GRAL. PAZ Y ULRICO SCHMIDL,-58.521731,-34.659975
222,Comuna 12,,True,SUPERI,SUPERI Y AV. GRAL. PAZ,-58.486715,-34.543212
366,Comuna 9,,True,DE LOS CORRALES AV.,"De Los Corrales Av. y Paz, Gral. Av.",-58.508775,-34.669777
376,Comuna 12,,True,"PAZ, GRAL. AV.",Av. Gral. Paz y Av. Dr. Ricardo Balbín,-58.500738,-34.549795
390,Comuna 12,,True,"PAZ, GRAL. AV.","Paz, Gral. Av. y Zapiola",-58.480986,-34.540731
416,Comuna 12,,True,"PAZ, GRAL. AV.",Av. Gral. Paz y Av. de los Constituyentes,-58.509930,-34.569197
445,Comuna 9,,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y ALBERDI, JUAN BAUTISTA AV.",-58.518399,-34.662525
480,Comuna 13,,True,"PAZ, GRAL. AV.",GRAL PAZ Y CABILDO,-58.476178,-34.538257
513,Comuna 13,,True,CABILDO AV.,"CABILDO AV. y PAZ, GRAL. AV.",-58.476178,-34.538257
570,Comuna 13,,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y DEL LIBERTADOR AV.",-58.467435,-34.534769
583,Comuna 8,,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y 27 DE FEBRERO AV.",-58.462450,-34.705250
628,Comuna 12,,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y BALBIN, RICARDO, DR. AV.",-58.500738,-34.549795
641,Comuna 4,,False,AUTOPISTA BUENOS AIRES - LA PLATA,"AU BUENOS AIRES LA PLATA KM 4,5",0.000000,0.000000
643,Comuna 8,,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. y DELLEPIANE, LUIS, TTE. GRAL",-58.486954,-34.687952
654,Comuna 11,,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y MOSCONI GENERAL AV.",-58.523406,-34.597988
658,Comuna 13,,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y DEL LIBERTADOR AV.",-58.467435,-34.534769
670,Comuna 8,,False,"PAZ, GRAL. AV.","PAZ, GRAL. AV. 14723",-58.495302,-34.680108
682,Comuna 9,,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y TONELERO",-58.529311,-34.654229
692,Comuna 12,,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y BALBIN, RICARDO, DR. AV.",-58.500738,-34.549795

Vemos una recurrencia de estos datos. La mayoría de los accidentes para estos valores se ubican en la Avenida Gral Paz, sabemos que la misma limita a la ciudad autonoma de buenos aires con la provincia.

Por ello, para respetar la información dada por las coordenadas geográficas modificaremos la columna 'Comuna' dejando los valores en 'Comuna 0' donde las coordenadas corresponden a un barrio vacío (columna 'Barrio').

Además pondremos 'Límite o afueras' en los valores vacíos de la columna 'Barrio'

In [18]:
# Condición para valores vacíos en 'Barrio'
condicion_barrio_vacio = (accidentes['Barrio'] == '')

# Asignamose 'Comuna 0' a 'Comuna' para valores vacíos en 'Barrio'
accidentes.loc[condicion_barrio_vacio, 'Comuna'] = 'Comuna 0'

# Rellena los valores vacíos en 'Barrio' con 'Límite o afueras'
accidentes.loc[condicion_barrio_vacio, 'Barrio'] = 'Límite o Afueras'

In [19]:
accidentes[accidentes.Comuna == 'Comuna 0'][['Comuna', 'Barrio', 'Cruce', 'Calle', 'Lugar Del Hecho', 'Pos X', 'Pos Y']]

,Comuna,Barrio,Cruce,Calle,Lugar Del Hecho,Pos X,Pos Y
1,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y AV DE LOS CORRALES,-58.508775,-34.669777
7,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV GENERAL PAZ Y AV DE LOS CORRALES,-58.508775,-34.669777
17,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y AV 27 DE FEBRERO,-58.462450,-34.705250
27,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV GRAL PAZ COLECTORA Y ZUVIRIA,-58.496835,-34.678927
33,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y AV DEL LIBERTADOR,-58.467435,-34.534769
39,Comuna 0,Límite o Afueras,False,"LUGONES, LEOPOLDO AV.",AUTOPISTA LUGONES PK 10000,0.000000,0.000000
41,Comuna 0,Límite o Afueras,True,AUTOPISTA DELLEPIANE LUIS TTE. GRAL.,AU LUIS DELLEPIANE Y AV GRAL PAZ,-58.486954,-34.687952
52,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y RODOLFO SCAPINO,-58.498966,-34.677321
69,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y AV LIBERTADOR,-58.467435,-34.534769
75,Comuna 0,Límite o Afueras,True,MOSCONI GENERAL AV.,AV GRAL MOSCONI Y AV GRAL PAZ,-58.523406,-34.597988
131,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV GRAL PAZ Y AV GENERAL MOSCONI,-58.523406,-34.597988
140,Comuna 0,Límite o Afueras,False,AUTOPISTA 25 DE MAYO,AUTOPISTA 25 DE MAYO,0.000000,0.000000
151,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV. GRAL. PAZ Y AV. R. BALBIN,-58.500738,-34.549795
158,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV. GRAL. PAZ Y AV. DE LOS CORRALES,-58.508775,-34.669777
188,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV. GRAL. PAZ Y GOLETA JULIA,-58.494138,-34.680957
203,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",AV. GRAL. PAZ Y ULRICO SCHMIDL,-58.521731,-34.659975
222,Comuna 0,Límite o Afueras,True,SUPERI,SUPERI Y AV. GRAL. PAZ,-58.486715,-34.543212
366,Comuna 0,Límite o Afueras,True,DE LOS CORRALES AV.,"De Los Corrales Av. y Paz, Gral. Av.",-58.508775,-34.669777
376,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",Av. Gral. Paz y Av. Dr. Ricardo Balbín,-58.500738,-34.549795
390,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.","Paz, Gral. Av. y Zapiola",-58.480986,-34.540731
416,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",Av. Gral. Paz y Av. de los Constituyentes,-58.509930,-34.569197
445,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y ALBERDI, JUAN BAUTISTA AV.",-58.518399,-34.662525
480,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.",GRAL PAZ Y CABILDO,-58.476178,-34.538257
513,Comuna 0,Límite o Afueras,True,CABILDO AV.,"CABILDO AV. y PAZ, GRAL. AV.",-58.476178,-34.538257
570,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y DEL LIBERTADOR AV.",-58.467435,-34.534769
583,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y 27 DE FEBRERO AV.",-58.462450,-34.705250
628,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y BALBIN, RICARDO, DR. AV.",-58.500738,-34.549795
641,Comuna 0,Límite o Afueras,False,AUTOPISTA BUENOS AIRES - LA PLATA,"AU BUENOS AIRES LA PLATA KM 4,5",0.000000,0.000000
643,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. y DELLEPIANE, LUIS, TTE. GRAL",-58.486954,-34.687952
654,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y MOSCONI GENERAL AV.",-58.523406,-34.597988
658,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y DEL LIBERTADOR AV.",-58.467435,-34.534769
670,Comuna 0,Límite o Afueras,False,"PAZ, GRAL. AV.","PAZ, GRAL. AV. 14723",-58.495302,-34.680108
682,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y TONELERO",-58.529311,-34.654229
692,Comuna 0,Límite o Afueras,True,"PAZ, GRAL. AV.","PAZ, GRAL. AV. Y BALBIN, RICARDO, DR. AV.",-58.500738,-34.549795

Finalmente, eliminaremos las columnas sin información relevante y reordenaremos las columnas.

In [20]:
accidentes.columns

Index(['Hechos_Id', 'Número De Victimas', 'Fecha', 'Año', 'Mes', 'Dia',
       'Día Semana', 'Estación', 'Hora', 'Franja Horaria', 'Lugar Del Hecho',
       'Tipo De Calle', 'Calle', 'Cruce', 'Dirección Normalizada', 'Comuna',
       'XY (CABA)', 'Pos X', 'Pos Y', 'Participantes', 'Víctima', 'Acusado',
       'Rol', 'Sexo', 'Edad', 'Rango Etario', 'Barrio'],
      dtype='object')

In [21]:
columnas_to_drop = ['XY (CABA)', 'Dirección Normalizada']

# Borrar Columnas
accidentes = accidentes.drop(columnas_to_drop, axis=1)

Hemos encontrado que hay barrios que no corresponden a su respectiva comuna. Para preservar la fidelidad de la ubicación geográfica vamos a corregir la columna 'Comuna' asignando la comuna a la que pertenece cada barrio.

In [22]:
# Creamos un diccionario que asigne cada barrio a su respectiva comuna
import numpy as np

aux_communas = {
    'Constitucion': 'Comuna 1', 'Montserrat': 'Comuna 1', 'Puerto Madero': 'Comuna 1', 'Retiro': 'Comuna 1', 'San Nicolas': 'Comuna 1', 'San Telmo': 'Comuna 1',
    'Recoleta': 'Comuna 2',
    'Balvanera': 'Comuna 3', 'San Cristobal': 'Comuna 3',
    'Barracas': 'Comuna 4', 'Boca': 'Comuna 4', 'Nueva Pompeya': 'Comuna 4', 'Parque Patricios': 'Comuna 4',
    'Almagro': 'Comuna 5', 'Boedo': 'Comuna 5',
    'Caballito': 'Comuna 6',
    'Flores': 'Comuna 7', 'Parque Chacabuco': 'Comuna 7',
    'Villa Lugano': 'Comuna 8', 'Villa Riachuelo': 'Comuna 8', 'Villa Soldati': 'Comuna 8',
    'Liniers': 'Comuna 9', 'Mataderos': 'Comuna 9', 'Parque Avellaneda': 'Comuna 9',
    'Floresta': 'Comuna 10', 'Monte Castro': 'Comuna 10', 'Velez Sarsfield': 'Comuna 10', 'Versalles': 'Comuna 10', 'Villa Luro': 'Comuna 10', 'Villa Real': 'Comuna 10',
    'Villa del Parque': 'Comuna 11', 'Villa Devoto': 'Comuna 11', 'Villa Gral. Mitre': 'Comuna 11', 'Villa Santa Rita': 'Comuna 11',
    'Coghlan': 'Comuna 12', 'Saavedra': 'Comuna 12', 'Villa Pueyrredon': 'Comuna 12', 'Villa Urquiza': 'Comuna 12',
    'Belgrano': 'Comuna 13', 'Colegiales': 'Comuna 13', 'Nunez': 'Comuna 13',
    'Palermo': 'Comuna 14',
    'Agronomia': 'Comuna 15', 'Chacarita': 'Comuna 15', 'Parque Chas': 'Comuna 15', 'Paternal': 'Comuna 15', 'Villa Crespo': 'Comuna 15', 'Villa Ortuzar': 'Comuna 15',
    'Límite o Afueras': 'Comuna 0'  
}

# Cambiamos valores de la columna 'Comuna' según la presencia de ciertos valores en la columna 'Barrio
accidentes['Comuna'] = np.where(accidentes['Barrio'].isin(aux_communas.keys()), accidentes['Barrio'].map(aux_communas), accidentes['Comuna'])


accidentes.head()

,Hechos_Id,Número De Victimas,Fecha,Año,Mes,Dia,Día Semana,Estación,Hora,Franja Horaria,...,Pos X,Pos Y,Participantes,Víctima,Acusado,Rol,Sexo,Edad,Rango Etario,Barrio
0,2016-0001,1,2016-01-01,2016,Enero,1,Viernes,Verano,04:00:00,4,...,-58.475340,-34.687570,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,19,19-25,Villa Riachuelo
1,2016-0002,1,2016-01-02,2016,Enero,2,Sábado,Verano,01:15:00,1,...,-58.508775,-34.669777,AUTO-PASAJEROS,AUTO,PASAJEROS,CONDUCTOR,MASCULINO,70,61+,Límite o Afueras
2,2016-0003,1,2016-01-03,2016,Enero,3,Domingo,Verano,07:00:00,7,...,-58.390403,-34.631894,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,30,26-40,Constitucion
3,2016-0004,1,2016-01-10,2016,Enero,10,Domingo,Verano,00:00:00,0,...,-58.465039,-34.680930,MOTO-SD,MOTO,SD,CONDUCTOR,MASCULINO,18,19-25,Villa Lugano
4,2016-0005,1,2016-01-21,2016,Enero,21,Jueves,Verano,05:20:00,5,...,-58.387183,-34.622466,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,29,26-40,Constitucion

In [23]:
nuevo_orden = [
    'Hechos_Id', 'Número De Victimas', 'Fecha', 'Año', 'Mes', 'Dia',
       'Día Semana', 'Estación', 'Hora', 'Franja Horaria', 'Lugar Del Hecho',
       'Tipo De Calle', 'Calle', 'Cruce', 'Comuna', 'Barrio', 'Pos X',	'Pos Y',
       'Participantes', 'Víctima', 'Acusado',
       'Rol', 'Sexo', 'Edad', 'Rango Etario'
]

accidentes = accidentes[nuevo_orden]
accidentes.head(3)

,Hechos_Id,Número De Victimas,Fecha,Año,Mes,Dia,Día Semana,Estación,Hora,Franja Horaria,...,Barrio,Pos X,Pos Y,Participantes,Víctima,Acusado,Rol,Sexo,Edad,Rango Etario
0,2016-0001,1,2016-01-01,2016,Enero,1,Viernes,Verano,04:00:00,4,...,Villa Riachuelo,-58.475340,-34.687570,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,19,19-25
1,2016-0002,1,2016-01-02,2016,Enero,2,Sábado,Verano,01:15:00,1,...,Límite o Afueras,-58.508775,-34.669777,AUTO-PASAJEROS,AUTO,PASAJEROS,CONDUCTOR,MASCULINO,70,61+
2,2016-0003,1,2016-01-03,2016,Enero,3,Domingo,Verano,07:00:00,7,...,Constitucion,-58.390403,-34.631894,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,30,26-40

Web Scrapping

Ahora. Vamos a hacer webcrapping para sacar información de la población de la Ciudad de Buenos Aires

In [24]:
# Obtenemos la URL con la información
url = 'https://es.wikipedia.org/wiki/Buenos_Aires'
response = requests.get(url)

In [25]:
soup = BeautifulSoup(response.text, 'html.parser')

Buscamos la tabla en la URL que contiene la información que necesitamos.

In [26]:
# Una variable llamada tabla se inicializa como None
tabla = None

# Buscamos todas las etiquetas de tabla (<table>) en el contenido HTML
tablas = soup.find_all('table')

# Itera a través de todas las tablas que se encuentran en la página web.
for table in tablas:
    
# Busca una etiqueta de encabezado (<th>) dentro de la tabla que tiene los atributos colspan='3' y class='navbox-title'
    encabezado = table.find('th', {'colspan': '3', 'class': 'navbox-title'})
    
    # Comprueba si se encontró un encabezado y si el texto del encabezado contiene "Población histórica"
    if encabezado and "Población histórica" in encabezado.text:
        # Si se cumple la condición anterior, asigne la tabla actual a la variable tabla y salga del bucle for con break
        tabla = table
        break

Cargamos la tabla

In [27]:
tabla

<table class="toccolours" style="width:15em;border-spacing: 0;float:right;clear:right;margin:0 0 1em 1em;"><tbody><tr><th class="navbox-title" colspan="3" style="padding:0.25em;font-size:110%">Población histórica</th></tr><tr style="font-size:95%"><th style="border-bottom:1px solid black;padding:1px;width:3em">Año</th><th style="border-bottom:1px solid black;padding:1px 2px;text-align:right"><abbr title="Población">Pob.</abbr></th><th style="border-bottom:1px solid black;padding:1px;text-align:right"><abbr title="Cambio porcentual">±%</abbr></th></tr><tr><th style="text-align:center;padding:1px">1779 </th><td style="text-align:right;padding:1px">24 205</td><td style="text-align:right;padding:1px">—    </td></tr><tr><th style="text-align:center;padding:1px">1810 </th><td style="text-align:right;padding:1px">44 800</td><td style="text-align:right;padding:1px">+85.1%</td></tr><tr><th style="text-align:center;padding:1px">1869 </th><td style="text-align:right;padding:1px">177 797</td><td style="text-align:right;padding:1px">+296.9%</td></tr><tr><th style="text-align:center;padding:1px">1895 </th><td style="text-align:right;padding:1px">663 854</td><td style="text-align:right;padding:1px">+273.4%</td></tr><tr><th style="text-align:center;padding:1px;border-bottom:1px solid #bbbbbb">1914 </th><td style="text-align:right;padding:1px;border-bottom:1px solid #bbbbbb">1 575 814</td><td style="text-align:right;padding:1px;border-bottom:1px solid #bbbbbb">+137.4%</td></tr><tr><th style="text-align:center;padding:1px">1947 </th><td style="text-align:right;padding:1px">2 981 043</td><td style="text-align:right;padding:1px">+89.2%</td></tr><tr><th style="text-align:center;padding:1px">1960 </th><td style="text-align:right;padding:1px">2 966 634</td><td style="text-align:right;padding:1px">−0.5%</td></tr><tr><th style="text-align:center;padding:1px">1970 </th><td style="text-align:right;padding:1px">2 972 453</td><td style="text-align:right;padding:1px">+0.2%</td></tr><tr><th style="text-align:center;padding:1px">1980 </th><td style="text-align:right;padding:1px">2 922 829</td><td style="text-align:right;padding:1px">−1.7%</td></tr><tr><th style="text-align:center;padding:1px;border-bottom:1px solid #bbbbbb">1991 </th><td style="text-align:right;padding:1px;border-bottom:1px solid #bbbbbb">2 965 403</td><td style="text-align:right;padding:1px;border-bottom:1px solid #bbbbbb">+1.5%</td></tr><tr><th style="text-align:center;padding:1px">2001 </th><td style="text-align:right;padding:1px">2 776 138</td><td style="text-align:right;padding:1px">−6.4%</td></tr><tr><th style="text-align:center;padding:1px">2010 </th><td style="text-align:right;padding:1px">2 890 151</td><td style="text-align:right;padding:1px">+4.1%</td></tr><tr><th style="text-align:center;padding:1px">2022 </th><td style="text-align:right;padding:1px">3 121 707</td><td style="text-align:right;padding:1px">+8.0%</td></tr></tbody></table>

Guardamos la tabla en un df

In [30]:
# Creamos listas para almacenar las columnas de la tabla.
años = []
poblaciones = []
cambios = []

# Inicializamos una variable en None
año_cualquiera = None

# Iteramos a través de las filas de la tabla.
for row in tabla.find_all('tr'):
    # Buscamos tanto th (encabezados) como td (celdas de datos)
    columns = row.find_all(['th', 'td'])

    #  Asegura de que haya suficientes columnas para extraer el año, la población y el cambio porcentual
    if len(columns) >= 3:
        año_cualquiera = columns[0].get_text(strip=True)  # Get Year
        poblacion = columns[1].get_text(strip=True)  # Get Population
        cambio = columns[2].get_text(strip=True)  # Get population changes

        # Agregamos valores a las listas respectivas
        años.append(año_cualquiera)  
        poblaciones.append(poblacion)  
        cambios.append(cambio)  

# Se crea un DataFrame de Pandas con los datos extraídos
Censo = pd.DataFrame({'Año': años, 'Poblacion': poblaciones, 'Cambio': cambios})

print("Dataframe guardado correctamente")

Dataframe guardado correctamente

In [31]:
Censo

     Año  Poblacion   Cambio
0    Año       Pob.       ±%
1   1779     24 205        —
2   1810     44 800   +85.1%
3   1869    177 797  +296.9%
4   1895    663 854  +273.4%
5   1914  1 575 814  +137.4%
6   1947  2 981 043   +89.2%
7   1960  2 966 634    −0.5%
8   1970  2 972 453    +0.2%
9   1980  2 922 829    −1.7%
10  1991  2 965 403    +1.5%
11  2001  2 776 138    −6.4%
12  2010  2 890 151    +4.1%
13  2022  3 121 707    +8.0%

Corregimos los datos del Dataframe.

In [32]:
# Se elimina la primera fila.
Censo = Censo.iloc[1:]

# Se elimina la columna 'Cambio'
Censo = Censo.drop('Cambio', axis=1)

# Los espacios de separación de miles se eliminan en la columna 'Población'
Censo['Poblacion'] = Censo['Poblacion'].str.replace(' ', '').str.replace('\xa0', '').astype(int)

# Convertimos la columna 'Año' a tipo entero
Censo['Año'] = Censo['Año'].astype(int)

# Reseteamos el indice
Censo = Censo.reset_index(drop=True)

Como solo tenemos datos de los censos de 2010 y 2022, utilizaremos el crecimiento poblacional anual promedio para estimar la población año por año.

In [33]:
# Obtenemos la población para el año 2010 si hay datos.
pop_2010 = Censo.loc[Censo['Año'] == 2010, 'Poblacion'].values[0] if len(Censo.loc[Censo['Año'] == 2010]) > 0 else None

# Obtenemos la población para el año 2022 si hay datos.
pop_2022 = Censo.loc[Censo['Año'] == 2022, 'Poblacion'].values[0] if len(Censo.loc[Censo['Año'] == 2022]) > 0 else None

# Verificamos si se obtuvieron datos antes de continuar
if pop_2010 is not None and pop_2022 is not None:
    # Calculamos la tasa de crecimiento anual promedio
    tasa_crecimiento = (pop_2022 / pop_2010) ** (1 / (2022 - 2010)) - 1

    # Generamos la lista de años del 2010 al 2022
    años = list(range(2010, 2023))

    # Calculamos la población para cada año usando la tasa de crecimiento.
    pobla_personas_año = [int(pop_2010 * (1 + tasa_crecimiento) ** (year - 2010)) for year in años]

    # Mostramos lista
    print(pobla_personas_año)
else:
    print("No hay datos para los valores de 2010 y 2022.")

[2890151, 2908773, 2927515, 2946377, 2965362, 2984468, 3003698, 3023052, 3042530, 3062134, 3081864, 3101721, 3121707]

In [39]:
data = {'Año': años, 'Población':pobla_personas_año}
Pobla_BsAs = pd.DataFrame(data)
Pobla_BsAs

     Año  Población
0   2010    2890151
1   2011    2908773
2   2012    2927515
3   2013    2946377
4   2014    2965362
5   2015    2984468
6   2016    3003698
7   2017    3023052
8   2018    3042530
9   2019    3062134
10  2020    3081864
11  2021    3101721
12  2022    3121707

In [40]:
Pobla_BsAs.drop(Pobla_BsAs.index[:6], inplace=True)

Pobla_BsAs.reset_index(drop=True, inplace=True)

Pobla_BsAs

    Año  Población
0  2016    3003698
1  2017    3023052
2  2018    3042530
3  2019    3062134
4  2020    3081864
5  2021    3101721
6  2022    3121707

Guardamos los datos en archivos cvs

In [41]:
dfs = [accidentes, Pobla_BsAs]
# Names corresponding to each DataFrame
names = ['accidentes_limpio', 'bsas_pobla']

ut.save_to_csv(dfs, names)

DataFrame 'accidentes_limpio' guardado como 'data/csv/accidentes_limpio.csv'
DataFrame 'bsas_pobla' guardado como 'data/csv/bsas_pobla.csv'